import { describe, expect, it } from 'vitest';
import {
	ConnectPointPosition,
	ConnectPointType,
	ElementType,
} from '@maklja/vision-simulator-model';
import {
	createConnectLine,
	createElement,
	createTestStore,
	spyOnConsole,
} from '../test-utils';
import { StageState } from './stage';

type Store = ReturnType<typeof createTestStore>;

const MOVEMENT_REGRESSION_ISSUE = 'https://github.com/maklja/vision/issues/72';
const DELETION_REGRESSION_ISSUE = 'https://github.com/maklja/vision/issues/73';

// Creating the root store consumes one UUID for the simulation id, so the first id generated by an
// editor interaction is the second value produced by the deterministic mock.
const STORE_CREATION_UUID = 1;

function deterministicUuid(index: number) {
	return `00000000-0000-4000-8000-${String(STORE_CREATION_UUID + index).padStart(12, '0')}`;
}

function outputOf(id: string) {
	return {
		id,
		connectPointType: ConnectPointType.Output,
		connectPosition: ConnectPointPosition.Right,
	};
}

function inputOf(id: string) {
	return {
		id,
		connectPointType: ConnectPointType.Input,
		connectPosition: ConnectPointPosition.Left,
	};
}

function loadOfAndMap(store: Store) {
	store.getState().loadElements([
		createElement(ElementType.Of, { id: 'of-1', x: 0, y: 0 }),
		createElement(ElementType.Map, { id: 'map-1', x: 300, y: 0 }),
	]);
	store.getState().loadConnectPoints(Object.values(store.getState().elements));
}

const DEFAULT_LINE_POINTS = [
	{ x: 110, y: 34 },
	{ x: 258, y: 34 },
];

function loadOfMapLine(store: Store, points = DEFAULT_LINE_POINTS) {
	store.getState().loadConnectLines([
		createConnectLine({
			id: 'cl-1',
			source: outputOf('of-1'),
			target: inputOf('map-1'),
			points,
		}),
	]);
}

function elementNames(store: Store) {
	return Object.values(store.getState().elements).map((el) => el.name);
}

describe('editor workflows', () => {
	describe('creation and connections', () => {
		it('creates an element from draft through commit, deriving connect points and restoring the select stage', () => {
			const store = createTestStore();

			store.getState().startElementDraw({ type: ElementType.Of, x: 25, y: 50 });
			expect(store.getState().state).toBe(StageState.DrawElement);
			const draft = store.getState().draftElement!;
			expect(draft).toMatchObject({ id: deterministicUuid(1), name: 'of_0', x: 25, y: 50 });

			store.getState().updateDraftElementPosition({ x: 40, y: 60 });
			expect(store.getState().draftElement).toMatchObject({ x: 40, y: 60 });

			store.getState().addDraftElement();

			const state = store.getState();
			expect(state.state).toBe(StageState.Select);
			expect(state.draftElement).toBeNull();
			expect(state.elements[draft.id]).toMatchObject({
				id: draft.id,
				type: ElementType.Of,
				x: 40,
				y: 60,
				visible: true,
			});
			expect(state.connectPoints[draft.id]).toHaveLength(4);
			expect(
				state.connectPoints[draft.id].find(
					(cp) => cp.position === ConnectPointPosition.Right,
				),
			).toMatchObject({ type: ConnectPointType.Output, x: 150, y: 94 });
		});

		it('cancels an element draft back to a clean select stage', () => {
			const store = createTestStore();

			store.getState().startElementDraw({ type: ElementType.Map, x: 10, y: 10 });
			store.getState().stopElementDraw();

			expect(store.getState().state).toBe(StageState.Select);
			expect(store.getState().draftElement).toBeNull();
			expect(store.getState().elements).toEqual({});
			expect(store.getState().connectPoints).toEqual({});
		});

		it('clears prior selection and exposes only compatible, non-saturated targets when drawing a connection', () => {
			const store = createTestStore();
			store.getState().loadElements([
				createElement(ElementType.Of, { id: 'of-1', x: 0, y: 0 }),
				createElement(ElementType.Map, { id: 'map-1', x: 300, y: 0 }),
				createElement(ElementType.Map, { id: 'map-2', x: 600, y: 0 }),
				createElement(ElementType.From, { id: 'from-1', x: 0, y: 200 }),
				createElement(ElementType.Interval, { id: 'interval-1', x: 300, y: 200 }),
			]);
			store.getState().loadConnectPoints(Object.values(store.getState().elements));
			loadOfMapLine(store);
			store.getState().markElementAsSelected('of-1');
			store.getState().markConnectLineAsSelected('cl-1');

			store.getState().startConnectLineDraw({
				sourceId: 'from-1',
				type: ConnectPointType.Output,
				position: ConnectPointPosition.Right,
				points: [{ x: 0, y: 200 }],
			});

			expect(store.getState().state).toBe(StageState.DrawConnectLine);
			// map-1 input is saturated, interval-1 is incompatible, of-1 outputs do not reach `from`.
			expect(store.getState().selectedElements).toEqual(['map-2']);
			expect(store.getState().selectedConnectLines).toEqual([]);
			expect(
				store
					.getState()
					.connectPoints['map-2'].find((cp) => cp.position === ConnectPointPosition.Left)
					?.visible,
			).toBe(true);
			expect(
				store
					.getState()
					.connectPoints['map-1'].find((cp) => cp.position === ConnectPointPosition.Left)
					?.visible,
			).toBe(false);
			expect(
				store.getState().connectPoints['interval-1'].some((cp) => cp.visible),
			).toBe(false);
			expect(store.getState().connectPoints['of-1'].every((cp) => !cp.visible)).toBe(true);
		});

		it('stops exposing targets once the source connect point is saturated', () => {
			const store = createTestStore();
			loadOfAndMap(store);
			loadOfMapLine(store);

			store.getState().startConnectLineDraw({
				sourceId: 'of-1',
				type: ConnectPointType.Output,
				position: ConnectPointPosition.Right,
				points: [{ x: 110, y: 34 }],
			});

			expect(store.getState().state).toBe(StageState.DrawConnectLine);
			expect(store.getState().draftConnectLine).not.toBeNull();
			expect(store.getState().selectedElements).toEqual([]);
			expect(
				Object.values(store.getState().connectPoints).every((points) =>
					points.every((cp) => !cp.visible),
				),
			).toBe(true);
		});

		it('commits a valid link, clears transient drawing state and highlighting, and restores the source selection', () => {
			const store = createTestStore();
			loadOfAndMap(store);
			store.getState().markElementAsSelected('of-1');

			store.getState().startConnectLineDraw({
				sourceId: 'of-1',
				type: ConnectPointType.Output,
				position: ConnectPointPosition.Right,
				points: [
					{ x: 110, y: 34 },
					{ x: 180, y: 34 },
				],
			});
			store.getState().updateConnectPoints({
				connectPointUpdates: [
					{ id: 'map-1', highlight: { [ConnectPointPosition.Left]: true } },
				],
			});
			expect(
				store
					.getState()
					.connectPoints['map-1'].find((cp) => cp.position === ConnectPointPosition.Left)
					?.highlight,
			).toBe(true);

			store.getState().linkConnectLineDraw({
				connectPointId: 'map-1-left',
				targetId: 'map-1',
				targetPoint: { x: 258, y: 34 },
				targetConnectPointType: ConnectPointType.Input,
				targetConnectPointPosition: ConnectPointPosition.Left,
			});

			const state = store.getState();
			expect(state.state).toBe(StageState.Select);
			expect(state.draftConnectLine).toBeNull();
			expect(Object.values(state.connectLines)).toHaveLength(1);
			expect(Object.values(state.connectLines)[0]).toMatchObject({
				index: 1,
				name: 'output_right',
				source: outputOf('of-1'),
				target: inputOf('map-1'),
				points: [
					{ x: 110, y: 34 },
					{ x: 180, y: 34 },
					{ x: 258, y: 34 },
				],
			});
			expect(state.selectedElements).toEqual(['of-1']);
			expect(state.selectedConnectLines).toEqual([]);
			expect(
				state.connectPoints['map-1'].find((cp) => cp.position === ConnectPointPosition.Left),
			).toMatchObject({ visible: false, highlight: false });
			expect(
				state.connectPoints['of-1'].find((cp) => cp.position === ConnectPointPosition.Right)
					?.visible,
			).toBe(true);
		});

		it('cancels a connection draft and returns to a consistent selection state', () => {
			const store = createTestStore();
			loadOfAndMap(store);

			store.getState().startConnectLineDraw({
				sourceId: 'of-1',
				type: ConnectPointType.Output,
				position: ConnectPointPosition.Right,
				points: [{ x: 110, y: 34 }],
			});
			store.getState().updateConnectPoints({
				connectPointUpdates: [
					{ id: 'map-1', highlight: { [ConnectPointPosition.Left]: true } },
				],
			});

			store.getState().stopConnectPointDraw();

			const state = store.getState();
			expect(state.state).toBe(StageState.Select);
			expect(state.draftConnectLine).toBeNull();
			expect(state.connectLines).toEqual({});
			expect(state.selectedElements).toEqual(['of-1']);
			expect(state.selectedConnectLines).toEqual([]);
			expect(
				state.connectPoints['map-1'].find((cp) => cp.position === ConnectPointPosition.Left),
			).toMatchObject({ visible: false, highlight: false });
		});
	});

	describe('selection and movement', () => {
		it('coordinates single selection, toggles, multi-selection, line selection, and clearing', () => {
			const store = createTestStore();
			loadOfAndMap(store);
			loadOfMapLine(store);

			store.getState().markElementAsSelected('of-1');
			expect(store.getState().selectedElements).toEqual(['of-1']);

			store.getState().toggleElementSelection('map-1');
			expect(store.getState().selectedElements).toEqual(['of-1', 'map-1']);

			store.getState().markConnectLineAsSelected('cl-1');
			store.getState().toggleConnectLineSelection('cl-1');
			store.getState().markConnectLineAsSelected('cl-1');
			expect(store.getState().selectedConnectLines).toEqual(['cl-1']);

			store.getState().clearAllSelectedElements();

			expect(store.getState().selectedElements).toEqual([]);
			expect(store.getState().selectedConnectLines).toEqual([]);
			expect(
				Object.values(store.getState().connectPoints).every((points) =>
					points.every((cp) => !cp.visible),
				),
			).toBe(true);
		});

		interface LassoDrag {
			label: string;
			start: { x: number; y: number };
			end: { x: number; y: number };
		}

		const lassoDirections: LassoDrag[] = [
			{ label: 'top-left to bottom-right', start: { x: -20, y: -20 }, end: { x: 150, y: 150 } },
			{ label: 'bottom-right to top-left', start: { x: 150, y: 150 }, end: { x: -20, y: -20 } },
			{ label: 'top-right to bottom-left', start: { x: 150, y: -20 }, end: { x: -20, y: 150 } },
			{ label: 'bottom-left to top-right', start: { x: -20, y: 150 }, end: { x: 150, y: -20 } },
		];

		it.each(lassoDirections)(
			'selects elements and intersecting lines for a $label lasso drag',
			({ start, end }) => {
				const store = createTestStore();
				loadOfAndMap(store);
				loadOfMapLine(store);

				store.getState().startLassoSelection(start);
				store.getState().updateLassoSelection(end);

				expect(store.getState().lassoSelection).toMatchObject({
					x: start.x,
					y: start.y,
					width: end.x - start.x,
					height: end.y - start.y,
				});

				store.getState().selectElementsInLassoBoundingBox();

				expect(store.getState().selectedElements).toEqual(['of-1']);
				expect(store.getState().selectedConnectLines).toEqual(['cl-1']);
				expect(
					store
						.getState()
						.connectPoints['of-1'].find(
							(cp) => cp.position === ConnectPointPosition.Right,
						)?.visible,
				).toBe(true);
			},
		);

		it.each(lassoDirections)(
			'clears the selection for an empty $label lasso drag',
			({ start, end }) => {
				const store = createTestStore();
				loadOfAndMap(store);
				loadOfMapLine(store);
				store.getState().markElementAsSelected('of-1');
				store.getState().markConnectLineAsSelected('cl-1');

				const offset = { x: start.x + 900, y: start.y + 900 };
				const offsetEnd = { x: end.x + 900, y: end.y + 900 };
				store.getState().startLassoSelection(offset);
				store.getState().updateLassoSelection(offsetEnd);

				store.getState().selectElementsInLassoBoundingBox();

				expect(store.getState().selectedElements).toEqual([]);
				expect(store.getState().selectedConnectLines).toEqual([]);
				expect(
					Object.values(store.getState().connectPoints).every((points) =>
						points.every((cp) => !cp.visible),
					),
				).toBe(true);
			},
		);

		it.skip(`moves a single element together with its connect points and attached line endpoints (${MOVEMENT_REGRESSION_ISSUE})`, () => {
			const store = createTestStore();
			loadOfAndMap(store);
			loadOfMapLine(store);

			store.getState().moveElement({ id: 'of-1', x: 100, y: 0 });

			const state = store.getState();
			expect(state.elements['of-1']).toMatchObject({ x: 100, y: 0 });
			expect(
				state.connectPoints['of-1'].find((cp) => cp.position === ConnectPointPosition.Right),
			).toMatchObject({ x: 210, y: 34 });
			expect(state.connectLines['cl-1'].points).toEqual([
				{ x: 210, y: 34 },
				{ x: 358, y: 34 },
			]);
		});

		it('characterizes the current single-element move behavior for dependent geometry', () => {
			const store = createTestStore();
			loadOfAndMap(store);
			loadOfMapLine(store);

			store.getState().moveElement({ id: 'of-1', x: 100, y: 0 });

			const state = store.getState();
			// The element position updates correctly.
			expect(state.elements['of-1']).toMatchObject({ x: 100, y: 0 });
			expect(state.elements['map-1']).toMatchObject({ x: 300, y: 0 });
			// Characterization of issue #72: dependent geometry keeps its original coordinates.
			expect(
				state.connectPoints['of-1'].find((cp) => cp.position === ConnectPointPosition.Right),
			).toMatchObject({ x: 110, y: 34 });
			expect(state.connectLines['cl-1'].points).toEqual([
				{ x: 110, y: 34 },
				{ x: 258, y: 34 },
			]);
		});

		it('moves the selected group, its connect points, attached endpoints, and internal points of selected lines', () => {
			const store = createTestStore();
			loadOfAndMap(store);
			loadOfMapLine(store, [
				{ x: 110, y: 34 },
				{ x: 180, y: 34 },
				{ x: 220, y: 34 },
				{ x: 258, y: 34 },
				{ x: 300, y: 34 },
			]);
			store.getState().setSelectElements(['of-1']);
			store.getState().markConnectLineAsSelected('cl-1');

			store.getState().moveSelectedElementsByDelta({
				referenceElementId: 'of-1',
				x: 10,
				y: 0,
			});

			const state = store.getState();
			expect(state.elements['of-1']).toMatchObject({ x: 10, y: 0 });
			expect(state.elements['map-1']).toMatchObject({ x: 300, y: 0 });
			expect(
				state.connectPoints['of-1'].find((cp) => cp.position === ConnectPointPosition.Right),
			).toMatchObject({ x: 120, y: 34 });
			expect(state.connectLines['cl-1'].points).toEqual([
				{ x: 120, y: 34 },
				{ x: 190, y: 34 },
				{ x: 230, y: 34 },
				{ x: 258, y: 34 },
				{ x: 300, y: 34 },
			]);
		});
	});

	describe('deletion and clipboard', () => {
		function loadDeletionGraph(store: Store) {
			store.getState().loadElements([
				createElement(ElementType.Of, { id: 'of-1', x: 0, y: 0 }),
				createElement(ElementType.Map, { id: 'map-1', x: 300, y: 0 }),
				createElement(ElementType.Map, { id: 'map-2', x: 600, y: 0 }),
			]);
			store.getState().loadConnectPoints(Object.values(store.getState().elements));
			store.getState().loadConnectLines([
				createConnectLine({
					id: 'cl-1',
					source: outputOf('of-1'),
					target: inputOf('map-1'),
					points: [
						{ x: 110, y: 34 },
						{ x: 258, y: 34 },
					],
				}),
				createConnectLine({
					id: 'cl-2',
					source: outputOf('map-1'),
					target: inputOf('map-2'),
					points: [
						{ x: 410, y: 34 },
						{ x: 558, y: 34 },
					],
				}),
			]);
		}

		it('removes selected elements, explicitly selected lines, incident lines, and connect points', () => {
			const store = createTestStore();
			loadDeletionGraph(store);
			store.getState().setSelectElements(['of-1']);
			store.getState().markConnectLineAsSelected('cl-2');

			store.getState().removeSelectedElements();

			const state = store.getState();
			expect(Object.keys(state.elements).sort()).toEqual(['map-1', 'map-2']);
			expect(state.connectPoints['of-1']).toBeUndefined();
			expect(state.connectPoints['map-1']).toHaveLength(4);
			expect(state.connectPoints['map-2']).toHaveLength(4);
			// cl-1 is incident to the removed element, cl-2 was explicitly selected.
			expect(state.connectLines).toEqual({});
		});

		it.skip(`clears stale selection ids after deletion (${DELETION_REGRESSION_ISSUE})`, () => {
			const store = createTestStore();
			loadDeletionGraph(store);
			store.getState().setSelectElements(['of-1']);
			store.getState().markConnectLineAsSelected('cl-2');

			store.getState().removeSelectedElements();

			expect(store.getState().selectedElements).toEqual([]);
			expect(store.getState().selectedConnectLines).toEqual([]);
		});

		it('characterizes the current stale selection ids left after deletion', () => {
			const store = createTestStore();
			loadDeletionGraph(store);
			store.getState().setSelectElements(['of-1']);
			store.getState().markConnectLineAsSelected('cl-2');

			store.getState().removeSelectedElements();

			// Characterization of issue #73: the graph is cleaned up but the selection is not.
			expect(store.getState().selectedElements).toEqual(['of-1']);
			expect(store.getState().selectedConnectLines).toEqual(['cl-2']);
		});

		it('copies both endpoint elements when only a connect line is selected', () => {
			const store = createTestStore();
			loadOfAndMap(store);
			loadOfMapLine(store);

			store.getState().markConnectLineAsSelected('cl-1');
			store.getState().copySelected();

			expect(store.getState().clipboard.connectLines.map((cl) => cl.id)).toEqual(['cl-1']);
			expect(store.getState().clipboard.elements.map((el) => el.id).sort()).toEqual([
				'map-1',
				'of-1',
			]);
		});

		it('pastes the copied group relative to its center with new ids, remapped lines and translated points', () => {
			const store = createTestStore();
			loadOfAndMap(store);
			loadOfMapLine(store);
			store.getState().markConnectLineAsSelected('cl-1');
			store.getState().copySelected();

			// Copied group bounding box is (0, 0)-(425, 100), so its center is (212.5, 50).
			store.getState().pasteSelected({ x: 0, y: 0 });

			const copiedOfId = deterministicUuid(1);
			const copiedMapId = deterministicUuid(2);
			const copiedLineId = deterministicUuid(3);

			const state = store.getState();
			expect(Object.keys(state.elements).sort()).toEqual(
				['map-1', 'of-1', copiedOfId, copiedMapId].sort(),
			);
			expect(state.elements[copiedOfId]).toMatchObject({
				type: ElementType.Of,
				name: 'of_0',
				x: -212.5,
				y: -50,
			});
			expect(state.elements[copiedMapId]).toMatchObject({
				type: ElementType.Map,
				name: 'map_0',
				x: 87.5,
				y: -50,
			});
			expect(new Set(elementNames(store)).size).toBe(elementNames(store).length);

			expect(state.connectLines[copiedLineId]).toMatchObject({
				source: { ...outputOf('of-1'), id: copiedOfId },
				target: { ...inputOf('map-1'), id: copiedMapId },
				points: [
					{ x: -102.5, y: -16 },
					{ x: 45.5, y: -16 },
				],
			});
			expect(state.selectedElements).toEqual([copiedOfId, copiedMapId]);
			expect(state.selectedConnectLines).toEqual([copiedLineId]);
			expect(state.connectPoints[copiedOfId]).toHaveLength(4);
			expect(state.connectPoints[copiedMapId]).toHaveLength(4);
		});

		it('ignores a paste with an empty clipboard', () => {
			const store = createTestStore();
			loadOfAndMap(store);
			const before = store.getState().elements;

			store.getState().pasteSelected({ x: 10, y: 10 });

			expect(store.getState().elements).toBe(before);
			expect(store.getState().connectLines).toEqual({});
		});

		it('reports and skips clipboard lines whose endpoints were not captured', () => {
			const console_ = spyOnConsole();
			const store = createTestStore();
			loadOfAndMap(store);

			const orphanLine = createConnectLine({
				id: 'cl-orphan',
				source: outputOf('ghost-source'),
				target: inputOf('ghost-target'),
				points: [
					{ x: 0, y: 0 },
					{ x: 10, y: 0 },
				],
			});
			store.setState((state) => {
				state.clipboard.elements = [
					createElement(ElementType.Of, { id: 'orphan-el', x: 0, y: 0 }),
				];
				state.clipboard.connectLines = [orphanLine];
			});

			store.getState().pasteSelected({ x: 500, y: 500 });

			expect(console_.error).toHaveBeenCalledWith(
				'Missing connect line element(s), source element id undefined, target element id undefined',
			);
			const state = store.getState();
			// The orphan connect line is skipped, but the captured element is still pasted.
			expect(state.connectLines).toEqual({});
			expect(Object.keys(state.elements)).toEqual(['of-1', 'map-1', deterministicUuid(1)]);

			console_.restore();
		});
	});

	describe('stage coordination', () => {
		it('loads a graph through the root store', () => {
			const store = createTestStore();

			store.getState().load(
				[
					createElement(ElementType.Of, { id: 'of-1', x: 0, y: 0 }),
					createElement(ElementType.Map, { id: 'map-1', x: 300, y: 0 }),
				],
				[
					createConnectLine({
						id: 'cl-1',
						source: outputOf('of-1'),
						target: inputOf('map-1'),
						points: [
							{ x: 110, y: 34 },
							{ x: 258, y: 34 },
						],
					}),
				],
			);

			const state = store.getState();
			expect(Object.keys(state.elements).sort()).toEqual(['map-1', 'of-1']);
			expect(state.connectPoints['of-1']).toHaveLength(4);
			expect(state.connectPoints['map-1']).toHaveLength(4);
			expect(Object.keys(state.connectLines)).toEqual(['cl-1']);
		});

		it('creates and clears snap lines while drawing', () => {
			const store = createTestStore();
			loadOfAndMap(store);

			store.getState().startElementDraw({ type: ElementType.Map, x: 300, y: 0 });
			const snapLines = store.getState().createDraftElementSnapLines({ x: 300, y: 0 });
			expect(snapLines.length).toBeGreaterThan(0);
			expect(store.getState().snapLines).toBe(snapLines);

			store.getState().startConnectLineDraw({
				sourceId: 'of-1',
				type: ConnectPointType.Output,
				position: ConnectPointPosition.Right,
				points: [{ x: 110, y: 34 }],
			});
			const targetConnectPoint = store
				.getState()
				.connectPoints['map-1'].find((cp) => cp.position === ConnectPointPosition.Left)!;
			const connectPointSnapLines = store.getState().createConnectPointSnapLines({
				x: targetConnectPoint.x + 16,
				y: targetConnectPoint.y + 16,
			});
			expect(connectPointSnapLines.length).toBeGreaterThan(0);

			store.getState().clearSnapLines();
			expect(store.getState().snapLines).toEqual([]);
		});

		it('coordinates tooltip, highlighting, canvas and theme through the root store', () => {
			const store = createTestStore();
			loadOfAndMap(store);

			store.getState().showTooltip({ elementId: 'of-1', text: 'hello' });
			expect(store.getState().tooltip).toEqual({ elementId: 'of-1', text: 'hello' });

			store.getState().hideTooltip();
			expect(store.getState().tooltip).toBeNull();

			store.getState().setHighlighted(['map-1']);
			expect(store.getState().highlighted).toEqual(['map-1']);

			store.getState().updateCanvasState({ x: 10, y: 20, scaleX: 2 });
			store.getState().updateCanvasState({ y: 30, snapToGrip: true });
			expect(store.getState().canvasState).toMatchObject({
				x: 10,
				y: 30,
				scaleX: 2,
				snapToGrip: true,
			});

			store.getState().changeTheme('beige');
			expect(store.getState().theme.default.colors.id).toBe('beige');
		});
	});
});
